### ISSUE TITLE
Ptolus Cyphers

### ISSUE THREAD

**Issue by morgurth** [mrkwnzl/cyphersystem-compendium#11]
"Potion of eagle eye" is misspelled as "Potion of egale eye"

"Potion of mage hand" is misspelled as "Potion of mage hands"

**Comment by mrkwnzl** [comment]
Looks like you drank a potion of eagle eye yourself 😉

Thanks! I’ll have it fixed shortly.

**Comment by mrkwnzl** [comment]
Fixed in v2.3.2

Thanks again!
