### ISSUE TITLE
Ptolus Cyphers Part 2

### ISSUE THREAD

**Issue by morgurth** [mrkwnzl/cyphersystem-compendium#13]
Thanks for fixing the others so fast. I should've waited until I finished making rollable tables. lol

Here's another one.

"Potion of rejunivation" should be "Potion of rejuvenation"
"Potion of superior rejunivation" should be "Potion of rejuvenation"

**Comment by mrkwnzl** [comment]
Awesome! Thank you so much! Fixed (along with the general rejuvenator cypher) in v2.3.3
