### ISSUE TITLE
Cyphers-Chaositech

### ISSUE THREAD

**Issue by morgurth** [mrkwnzl/cyphersystem-compendium#16]
The "Bomb, void" level should be 1d6+3, not 1d6+2 (which is what the other bombs are).

Also, the level is set to "6", so when you drag it to an actor and identify it, it doesn't roll the level.

**Comment by mrkwnzl** [comment]
> Also, the level is set to "6", so when you drag it to an actor and identify it, it doesn't roll the level.

My version says 1d6+3 there. In the description, it’s 1d6+2, though.

**Comment by mrkwnzl** [comment]
Chaositech artifacts have been removed in v3.0.0
