### ISSUE TITLE
Efficacy Boost Cypher not correct for CSR

### ISSUE THREAD

**Issue by farling42** [mrkwnzl/cyphersystem-compendium#18]
There is a single Efficacy Boost cypher in the "Cyphers (Power Boost)" compendium, and it references pages in both the CSR and Claim the Sky,

The CSR actually has "Efficacy Boost (Major)" and "Efficacy Boost (Minor)" as two separate cyphers, so it would be nice if the compendium contained these two entries as well.

(This is because I'm creating a table for The Origin which makes mention of wanting to roll on either the Claim the Sky power boost cypher table or the CSR power boost cypher table.)

**Comment by mrkwnzl** [comment]
Good point. Will update on the weekend.

**Comment by mrkwnzl** [comment]
Fixed in v3.0.0
