### ISSUE TITLE
Errors in Abilities compendium: Nightmare, Death Touch, Flex Skill

### ISSUE THREAD

**Issue by farling42** [mrkwnzl/cyphersystem-compendium#9]
When putting together the journal entry compendiums for NTSY Cypher Add-Ons, I noticed the following in the cyphersystem-compendium:

Two abilities from the CSR are missing:
- **Nightmare** (CSR page 165)
- **Death Touch** (CSR page 125)

There are two entries for **Flex Skill**, and both contain a reference to FR page 20. There should only be a single entry, and it should point to both CSR page 141 and FR page 20.

**Comment by mrkwnzl** [comment]
Thanks! Fixed in 2.3.1
